# Generated by Django 6.0.4 on 2026-04-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cont01app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10),
        ),
    ]
