# Generated by Django 6.0.4 on 2026-04-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cont01app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='countermembership',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='counter',
            name='status',
        ),
        migrations.AddConstraint(
            model_name='countermembership',
            constraint=models.UniqueConstraint(fields=('user', 'counter'), name='unique_user_counter_membership'),
        ),
    ]
